spring.application.name=demoAgent

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4o
openai.base-url=https://api.openai.com/v1

spring.datasource.url=jdbc:sqlite:./tools.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
