spring.application.name=demoAgent

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4o
openai.base-url=https://api.openai.com/v1

tool.urls.random=${TOOL_URL_RANDOM:http://localhost:8081}
tool.urls.currency=${TOOL_URL_CURRENCY:http://localhost:8082}
tool.urls.weather=${TOOL_URL_WEATHER:http://localhost:8083}
